[package]
name = "ttt-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ttt-sys = { git = "https://github.com/hwoy/ttt-sys.git" }
